### ISSUE TITLE
Decompilation issues?

### ISSUE THREAD

**Issue by MeblIkea** [oslo1989/ableton-control-surface-toolkit#1]
Hello, 
I've been trying to create a modified version of the Push 1 script to add some features, but when just renaming it to Push1000 and putting in `User Library\Remote Scripts\`, it raises an error (see below).

```
2024-10-27T23:24:46.386751: error: RemoteScriptError: Traceback (most recent call last):

2024-10-27T23:24:46.386783: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push1000\__init__.py", line 43, in create_instance

2024-10-27T23:24:46.386971: error: RemoteScriptError:     
2024-10-27T23:24:46.386989: error: RemoteScriptError: return Push(c_instance=c_instance)
2024-10-27T23:24:46.387000: error: RemoteScriptError: 

2024-10-27T23:24:46.387017: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push1000\push.py", line 99, in __init__

2024-10-27T23:24:46.387191: error: RemoteScriptError:     
2024-10-27T23:24:46.387207: error: RemoteScriptError: (super().__init__)(*a, **k)
2024-10-27T23:24:46.387218: error: RemoteScriptError: 

2024-10-27T23:24:46.387234: error: RemoteScriptError:   File "..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\pushbase\push_base.py", line 167, in __init__

2024-10-27T23:24:46.387550: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push1000\push.py", line 857, in _create_controls

2024-10-27T23:24:46.388102: error: RemoteScriptError:     
2024-10-27T23:24:46.388124: error: RemoteScriptError: full_velocity=(self._c_instance.full_velocity),
2024-10-27T23:24:46.388136: error: RemoteScriptError: 

2024-10-27T23:24:46.388155: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push1000\elements.py", line 28, in __init__

2024-10-27T23:24:46.388345: error: RemoteScriptError:     
2024-10-27T23:24:46.388361: error: RemoteScriptError: **k,
2024-10-27T23:24:46.388372: error: RemoteScriptError: 

2024-10-27T23:24:46.388464: error: RemoteScriptError: TypeError
2024-10-27T23:24:46.388481: error: RemoteScriptError: : 
2024-10-27T23:24:46.388495: error: RemoteScriptError: __init__() got multiple values for argument 'deleter'
2024-10-27T23:24:46.388509: error: RemoteScriptError: 
```

I've also tried the Push 2 scripts for a friend, and it seems to raise an error too, but a different one.
```
2024-10-27T23:24:35.843514: error: RemoteScriptError: Traceback (most recent call last):

2024-10-27T23:24:35.843551: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push2000\__init__.py", line 27, in create_instance

2024-10-27T23:24:35.843768: error: RemoteScriptError:     
2024-10-27T23:24:35.843787: error: RemoteScriptError: from .push2 import Push2
2024-10-27T23:24:35.843799: error: RemoteScriptError: 

2024-10-27T23:24:35.843818: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push2000\push2.py", line 53, in <module>

2024-10-27T23:24:35.843982: error: RemoteScriptError:     
2024-10-27T23:24:35.844001: error: RemoteScriptError: from .browser_component import BrowserComponent, NewTrackBrowserComponent
2024-10-27T23:24:35.844013: error: RemoteScriptError: 

2024-10-27T23:24:35.844029: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push2000\browser_component.py", line 32, in <module>

2024-10-27T23:24:35.844204: error: RemoteScriptError:     
2024-10-27T23:24:35.844228: error: RemoteScriptError: from .browser_list import BrowserList
2024-10-27T23:24:35.844240: error: RemoteScriptError: 

2024-10-27T23:24:35.844258: error: RemoteScriptError:   File "C:\Users\Meb\Documents\Ableton\User Library\Remote Scripts\Push2000\browser_list.py", line 12, in <module>

2024-10-27T23:24:35.844420: error: RemoteScriptError:     
2024-10-27T23:24:35.844437: error: RemoteScriptError: from model.uniqueid import UniqueIdMixin
2024-10-27T23:24:35.844449: error: RemoteScriptError: 

2024-10-27T23:24:35.844468: error: RemoteScriptError: ModuleNotFoundError
2024-10-27T23:24:35.844481: error: RemoteScriptError: : 
2024-10-27T23:24:35.844493: error: RemoteScriptError: No module named 'model'
2024-10-27T23:24:35.844505: error: RemoteScriptError: 
```

I hope you can do something for me :D 
Thanks!

**Comment by MartinSahlen** [comment]
Not sure what you are trying to do here. But just to be clear, this decompiled code is only meant to be used for typing support, documentation generation and auto completion as well aid to understand better the code of Ableton control surfaces. I did not intend for this code to be used and extended directly as it will most certainly break.

**Comment by MeblIkea** [comment]
My bad,
I had read somewhere that someone managed to add features to the Push 1 using its decompiled files, but I think that what they actually did is using decompiled files among the compiled files, depending on what they wanted to change (Ik I'm terrible at explaining), but I think I know how I should do what I want to do.
Thanks!
